"""PartyPilot application services."""

from partypilot.application.baseline_comparison import (
    BaselineComparisonResult,
    BaselineComparisonRunner,
    BaselineObjectiveMetrics,
    render_baseline_comparison_markdown,
    save_baseline_comparison_reports,
)
from partypilot.application.baseline_experiment import (
    BaselineExperimentResult,
    SinglePassScenarioResult,
    render_baseline_experiment_markdown,
    run_baseline_experiment,
    save_baseline_experiment_reports,
)
from partypilot.application.budget_validation import (
    BudgetValidationResult,
    BudgetViolation,
    BudgetViolationCode,
    CostComponent,
    calculate_total_cost,
    validate_budget,
)
from partypilot.application.candidate_filtering import (
    CandidateFilterResult,
    CandidateRejection,
    CandidateRequirements,
    RejectionCode,
    filter_candidates,
)
from partypilot.application.citation_validation import (
    CitationValidationResult,
    CitationViolation,
    CitationViolationCode,
    validate_citations,
)
from partypilot.application.constraint_engine import (
    ConstraintEngineInput,
    ConstraintEngineResult,
    ConstraintEngineViolation,
    ConstraintEngineViolationCode,
    validate_constraints,
)
from partypilot.application.derived_constraints import (
    DerivedConstraint,
    DerivedConstraintContext,
    DerivedConstraintError,
    DerivedConstraintResult,
    derive_constraint,
)
from partypilot.application.deterministic_planner import (
    DeterministicPlanner,
    PlanCandidate,
    PlannerConfig,
    PlannerResult,
    PreferenceWeights,
)
from partypilot.application.evaluation_runner import (
    DeterministicEvaluationRunner,
    EvaluationMetrics,
    EvaluationRunResult,
    ScenarioEvaluation,
    calculate_metrics,
    render_markdown_summary,
    save_evaluation_reports,
)
from partypilot.application.evidence_grounded_planner import (
    EvidenceGroundedPlanCandidate,
    EvidenceGroundedPlanner,
    EvidenceGroundedPlannerConfig,
    EvidenceGroundedPlanningResult,
)
from partypilot.application.evidence_state_resolution import (
    EvidenceAssessment,
    EvidenceResolution,
    resolve_evidence_state,
)
from partypilot.application.query_rewriting_experiment import (
    ConditionalQueryRewriter,
    LexicalSignalPreservingRewriter,
    QueryRewriteDecisionRule,
    QueryRewriteExperimentReport,
    QueryRewriteMetrics,
    QueryRewriteVariantResult,
    render_query_rewriting_markdown,
    run_query_rewriting_experiment,
    write_query_rewriting_reports,
)
from partypilot.application.reranking_decision_experiment import (
    RerankingDecisionReport,
    RerankingDiagnosticMetrics,
    RerankingDiagnosticRule,
    render_reranking_decision_markdown,
    run_reranking_decision_experiment,
    write_reranking_decision_reports,
)
from partypilot.application.retrieval_benchmark import (
    DeterministicHashEmbeddingProvider,
    RetrievalBenchmarkCase,
    RetrievalBenchmarkMetrics,
    RetrievalBenchmarkReport,
    RetrievalBenchmarkVariantResult,
    build_retrieval_benchmark_cases,
    evaluate_retriever,
    render_markdown_report,
    write_retrieval_benchmark_reports,
)
from partypilot.application.single_pass_llm_planner import (
    LLMPlanFailureCategory,
    SinglePassLLMPlanner,
    SinglePassLLMResult,
    SinglePassPlannerError,
    SinglePassPlannerProviderError,
)
from partypilot.application.state_invalidation import (
    StateInvalidationResult,
    affected_dependency_kinds_for_updates,
    apply_updates,
    build_replanning_metrics,
)
from partypilot.application.targeted_replanning import (
    PlanningReplanningComparison,
    PlanningReplanResult,
    ReplanningStrategy,
    apply_full_replanning,
    apply_targeted_replanning,
    compare_replanning_strategies,
)
from partypilot.application.v02_evaluation import (
    BaselineMetricsSnapshot,
    RetrievalMetricsSnapshot,
    V02EvaluationMetrics,
    V02EvaluationReport,
    V02EvaluationRunner,
    V02ScenarioEvaluation,
    load_retrieval_snapshots,
    load_v01_baseline_snapshot,
    render_v02_evaluation_markdown,
    save_v02_evaluation_reports,
)
from partypilot.application.v03_replanning import (
    ARCHITECTURE_VARIANT as V03_REPLANNING_ARCHITECTURE_VARIANT,
)
from partypilot.application.v03_replanning import (
    BENCHMARK_NAME as V03_REPLANNING_BENCHMARK_NAME,
)
from partypilot.application.v03_replanning import (
    BENCHMARK_VERSION as V03_REPLANNING_BENCHMARK_VERSION,
)
from partypilot.application.v03_replanning import (
    DEFAULT_OUTPUT_ROOT as V03_REPLANNING_DEFAULT_OUTPUT_ROOT,
)
from partypilot.application.v03_replanning import (
    ReplanningBenchmarkScenario,
    ReplanningExperimentMetrics,
    ReplanningMetricDefinition,
    ReplanningScenarioResult,
    ReplanningScenarioStrategyMetrics,
    ReplanningStrategyMetrics,
    V03ReplanningReport,
    build_replanning_metadata,
    load_v03_replanning_benchmark,
    render_v03_replanning_markdown,
    run_v03_replanning_experiment,
    save_v03_replanning_reports,
)
from partypilot.application.v03_replanning import (
    default_output_dir as default_v03_replanning_output_dir,
)
from partypilot.application.v04_multi_agent import (
    BASELINE_ARCHITECTURE as V04_MULTI_AGENT_BASELINE_ARCHITECTURE,
)
from partypilot.application.v04_multi_agent import (
    BENCHMARK_NAME as V04_MULTI_AGENT_BENCHMARK_NAME,
)
from partypilot.application.v04_multi_agent import (
    BENCHMARK_VERSION as V04_MULTI_AGENT_BENCHMARK_VERSION,
)
from partypilot.application.v04_multi_agent import (
    DEFAULT_OUTPUT_ROOT as V04_MULTI_AGENT_DEFAULT_OUTPUT_ROOT,
)
from partypilot.application.v04_multi_agent import (
    MULTI_AGENT_ARCHITECTURE as V04_MULTI_AGENT_ARCHITECTURE,
)
from partypilot.application.v04_multi_agent import (
    V04ComparisonReport,
    V04ExperimentMetrics,
    V04MetricDefinition,
    V04ScenarioResult,
    V04StrategyMetrics,
    build_v04_metadata,
    load_v04_multi_agent_benchmark,
    render_v04_multi_agent_markdown,
    run_v04_multi_agent_experiment,
    save_v04_multi_agent_reports,
)

__all__ = [
    "V03_REPLANNING_ARCHITECTURE_VARIANT",
    "V03_REPLANNING_BENCHMARK_NAME",
    "V03_REPLANNING_BENCHMARK_VERSION",
    "V03_REPLANNING_DEFAULT_OUTPUT_ROOT",
    "V04_MULTI_AGENT_ARCHITECTURE",
    "V04_MULTI_AGENT_BASELINE_ARCHITECTURE",
    "V04_MULTI_AGENT_BENCHMARK_NAME",
    "V04_MULTI_AGENT_BENCHMARK_VERSION",
    "V04_MULTI_AGENT_DEFAULT_OUTPUT_ROOT",
    "BaselineComparisonResult",
    "BaselineComparisonRunner",
    "BaselineExperimentResult",
    "BaselineMetricsSnapshot",
    "BaselineObjectiveMetrics",
    "BudgetValidationResult",
    "BudgetViolation",
    "BudgetViolationCode",
    "CandidateFilterResult",
    "CandidateRejection",
    "CandidateRequirements",
    "CitationValidationResult",
    "CitationViolation",
    "CitationViolationCode",
    "ConditionalQueryRewriter",
    "ConstraintEngineInput",
    "ConstraintEngineResult",
    "ConstraintEngineViolation",
    "ConstraintEngineViolationCode",
    "CostComponent",
    "DerivedConstraint",
    "DerivedConstraintContext",
    "DerivedConstraintError",
    "DerivedConstraintResult",
    "DeterministicEvaluationRunner",
    "DeterministicHashEmbeddingProvider",
    "DeterministicPlanner",
    "EvaluationMetrics",
    "EvaluationRunResult",
    "EvidenceAssessment",
    "EvidenceGroundedPlanCandidate",
    "EvidenceGroundedPlanner",
    "EvidenceGroundedPlannerConfig",
    "EvidenceGroundedPlanningResult",
    "EvidenceResolution",
    "LLMPlanFailureCategory",
    "LexicalSignalPreservingRewriter",
    "PlanCandidate",
    "PlannerConfig",
    "PlannerResult",
    "PlanningReplanResult",
    "PlanningReplanningComparison",
    "PreferenceWeights",
    "QueryRewriteDecisionRule",
    "QueryRewriteExperimentReport",
    "QueryRewriteMetrics",
    "QueryRewriteVariantResult",
    "RejectionCode",
    "ReplanningBenchmarkScenario",
    "ReplanningExperimentMetrics",
    "ReplanningMetricDefinition",
    "ReplanningScenarioResult",
    "ReplanningScenarioStrategyMetrics",
    "ReplanningStrategy",
    "ReplanningStrategyMetrics",
    "RerankingDecisionReport",
    "RerankingDiagnosticMetrics",
    "RerankingDiagnosticRule",
    "RetrievalBenchmarkCase",
    "RetrievalBenchmarkMetrics",
    "RetrievalBenchmarkReport",
    "RetrievalBenchmarkVariantResult",
    "RetrievalMetricsSnapshot",
    "ScenarioEvaluation",
    "SinglePassLLMPlanner",
    "SinglePassLLMResult",
    "SinglePassPlannerError",
    "SinglePassPlannerProviderError",
    "SinglePassScenarioResult",
    "StateInvalidationResult",
    "V02EvaluationMetrics",
    "V02EvaluationReport",
    "V02EvaluationRunner",
    "V02ScenarioEvaluation",
    "V03ReplanningReport",
    "V04ComparisonReport",
    "V04ExperimentMetrics",
    "V04MetricDefinition",
    "V04ScenarioResult",
    "V04StrategyMetrics",
    "affected_dependency_kinds_for_updates",
    "apply_full_replanning",
    "apply_targeted_replanning",
    "apply_updates",
    "build_replanning_metadata",
    "build_replanning_metrics",
    "build_retrieval_benchmark_cases",
    "build_v04_metadata",
    "calculate_metrics",
    "calculate_total_cost",
    "compare_replanning_strategies",
    "default_v03_replanning_output_dir",
    "derive_constraint",
    "evaluate_retriever",
    "filter_candidates",
    "load_retrieval_snapshots",
    "load_v01_baseline_snapshot",
    "load_v03_replanning_benchmark",
    "load_v04_multi_agent_benchmark",
    "render_baseline_comparison_markdown",
    "render_baseline_experiment_markdown",
    "render_markdown_report",
    "render_markdown_summary",
    "render_query_rewriting_markdown",
    "render_reranking_decision_markdown",
    "render_v02_evaluation_markdown",
    "render_v03_replanning_markdown",
    "render_v04_multi_agent_markdown",
    "resolve_evidence_state",
    "run_baseline_experiment",
    "run_query_rewriting_experiment",
    "run_reranking_decision_experiment",
    "run_v03_replanning_experiment",
    "run_v04_multi_agent_experiment",
    "save_baseline_comparison_reports",
    "save_baseline_experiment_reports",
    "save_evaluation_reports",
    "save_v02_evaluation_reports",
    "save_v03_replanning_reports",
    "save_v04_multi_agent_reports",
    "validate_budget",
    "validate_citations",
    "validate_constraints",
    "write_query_rewriting_reports",
    "write_reranking_decision_reports",
    "write_retrieval_benchmark_reports",
]
